### ISSUE TITLE
Support GitLab if Possible

### ISSUE THREAD

**Issue by Zren** [Zren/plasma-applet-githubissues#1]
![](https://i.imgur.com/X0el13B.png)

The GitLab API is a little different than the GitHub API. I'd need to fetch 2 requests (issues + merge requests), then merge them sorted by most recent. I'd also have to add a new configuration field for the domain of the gitlab instance.

* https://docs.gitlab.com/ee/api/issues.html
* https://docs.gitlab.com/ee/api/merge_requests.html
* https://gitlab.com/api/v4/projects/gitlab-org%2Frelease%2Ftasks/issues
* https://gitlab.com/api/v4/projects/gitlab-org%2Frelease%2Ftasks/merge_requests
* https://git.opendesktop.org/api/v4/projects/OCS%2Focs-store/issues
* https://invent.kde.org/api/v4/projects/kde%2Fkdeconnect-kde/issues

**Comment by Zren** [comment]
https://github.com/Zren/plasma-applet-gitlabissues

**Comment by ratijas** [comment]
Hi,

Thanks for the applet. It's looking cool on desktop.

It there any reason for having GitHub and GitLab applets as two separate packages?

**Comment by Zren** [comment]
The APIs are different. If I wanted to I could abstract the common elements and make a 1 huge widget, but that'd be annoying to work on. I also wrote a [phabricator widget](https://github.com/Zren/plasma-applet-phabricatorrevisions) which requires you provide an API token.

**Comment by ratijas** [comment]
Gerrit support would be nice too. I wonder how that would look like, for example, with Qt repositories.
