### ISSUE TITLE
Cannot use Settings

### ISSUE THREAD

**Issue by lpegoraro** [Zren/plasma-applet-githubissues#11]
![Screenshot_20191001_130628](https://user-images.githubusercontent.com/6593889/65979925-92059e80-e44c-11e9-891c-ba1f75333777.png)

Reading package lists... Done
Building dependency tree       
Reading state information... Done
qml-module-org-kde-kirigami2 is already the newest version (5.44.0-0ubuntu1).

Help?

**Comment by Zren** [comment]
KDE Frameworks v5.44 only has `Kirigami.FormLayout 2.3`.

* https://github.com/KDE/kirigami/blob/v5.44.0/src/qmldir#L17

I've no idea if it'll work with the older version of Kirigami, but try editing `~/.local/share/plasma/plasmoids/com.github.zren.githubissues/contents/ui/config/ConfigGeneral.qml` to use `2.3`. Reopen the widget's config to test.

**Comment by lpegoraro** [comment]
I will try, thanks!

**Comment by Zren** [comment]
Uses Kirigami 2.3 in githubissues v4.
