### ISSUE TITLE
V3使用问题

### ISSUE THREAD

**Issue by debugbb** [Zren/plasma-applet-githubissues#14]
请问有没有使用说明，配置中没有找到链接Github的地方，谢谢！
Translate：
Title：
V3 usage problem
Body：
Is there any instruction for use? There is no link to Github in the configuration. Thank you

**Comment by Zren** [comment]
Here is an example:

![2019-10-23___19-34-45](https://user-images.githubusercontent.com/416367/67441833-749b9e80-f5cc-11e9-98f9-dee4bfd533e9.png)

**Comment by debugbb** [comment]
我就是这么填的，但是没有接收到issues。
我再试试，谢谢!
Translate：
That's how I filled it in, but I didn't receive issues.I'll try again, thanks

**Comment by debugbb** [comment]
It works，Thanks！
