### ISSUE TITLE
Plasmoid icon from Plasma Theme

### ISSUE THREAD

**Issue by varlesh** [Zren/plasma-applet-githubissues#7]
Will be good added support use tray icon from plasma theme and original icon as fallback.
Now this hardcoded:
```
	Plasmoid.icon: plasmoid.file("", "icons/octicon-mark-github.svg")
```

**Comment by varlesh** [comment]
Also CSS style not supported too ((
`ColorScheme-Text` must be used text from plasma color scheme. But this ignored on widget icon and used original color `#4d4d4d`

**Comment by varlesh** [comment]
![image](https://user-images.githubusercontent.com/8083855/53391585-4075cc80-39b0-11e9-9d93-d1005ac869e2.png)

**Comment by Zren** [comment]
Ah, this means I need to define the `Plasmoid.compactRepresentation` using [my AppletIcon workaround](https://github.com/Zren/plasma-applet-presentwindows/blob/master/package/contents/ui/lib/AppletIcon.qml). It still hardcodes the svg path, but it'll use the correct color scheme.

I use `ColorScheme-Text`, but I forgot the default compactRepresentation uses `PlasmaCore.IconItem` which doesn't apply the color scheme to svg's loaded from an absolute filepath. It only applies it to "icon names" without the file extension + path that are loaded from your icon theme.

* https://github.com/Zren/plasma-applet-githubissues/blob/v2/package/contents/icons/octicon-mark-github.svg?short_path=fbe74e2
* https://github.com/KDE/plasma-desktop/blob/master/desktoppackage/contents/applet/DefaultCompactRepresentation.qml

* https://github.com/KDE/plasma-framework/blame/master/src/declarativeimports/core/iconitem.cpp#L133
* https://github.com/KDE/kiconthemes/blob/master/src/kiconloader.cpp#L922
* https://github.com/KDE/plasma-framework/blob/master/src/plasma/svg.cpp#L88

Hmmmm...

This looks interesting though... it seems it might be able to load it from the "images" folder.

* https://github.com/KDE/plasma-framework/blob/master/src/plasma/svg.cpp#L431
* https://github.com/KDE/plasma-framework/blob/master/src/plasma/packagestructure/packages.cpp#L84

I tried renaming my `contents/icons/` folder to `contents/images/`. While the following code works, it still doesn't load follow the color scheme, as it's still returning an absolute filepath.

```qml
Plasmoid.icon: plasmoid.file("images", "octicon-mark-github.svg")
```

And neither of these loads the svg, which means I don't fully understand how `iconitem.cpp` works.

```qml
Plasmoid.icon: "octicon-mark-github"
Plasmoid.icon: "octicon-mark-github.svg"
```

I'd need to recompile `plasma-framework` with a ton of `qDebug() << "test";` to find out how that string is treated...

**Comment by varlesh** [comment]
@Zren if you interested, i'm draw Breeze style icons (dark and light)... Another way - you can add option switch icon for light/dark color scheme.
preview:
![image](https://user-images.githubusercontent.com/8083855/54677213-dddd9f80-4b1b-11e9-8867-bc13df4359be.png)
sources SVG:
[icons.tar.gz](https://github.com/Zren/plasma-applet-githubissues/files/2987666/icons.tar.gz)

**Comment by varlesh** [comment]
@Zren Yes, now colorscheme worked... but need fix icon size:
![image](https://user-images.githubusercontent.com/8083855/54695693-db8f3b80-4b43-11e9-9778-ccc1872e3704.png)
I'm update svg:
[octicon-mark-github.tar.gz](https://github.com/Zren/plasma-applet-githubissues/files/2988857/octicon-mark-github.tar.gz)
![image](https://user-images.githubusercontent.com/8083855/54696369-1c3b8480-4b45-11e9-9c17-61cff5113526.png)

**Comment by Zren** [comment]
Ah good point, normal svg icons usually have a 2px padding in their paths and mine was going right to the edge.

![2019-03-20___12-16-40](https://user-images.githubusercontent.com/416367/54700791-107e9c80-4b0a-11e9-9472-24d90c8ff750.png)

**Comment by Zren** [comment]
Icon fixed in the v3 release.
